package xom.example.android.elab_project.myClass;

/**
 * Created by Mawinda on 28-Jan-18.
 */

public class Mystrings {
    public static final String[] insuranceCompany = {"Choose Company..", "NHIF", "JUBILEE INS"};
    public static final String[] specimens = {"Choose Specimen...", "Urine", "Saliva", "Blood", "Stool"};
    public static final String[] testTypes = {
            "Select test ...",
            "β2-Glycoprotein 1 Antibodies",
            "β2-Microglobulin",
            "1,25 dihydroxyvitamin D",
            "3-ANCA",
            "3-day Measles",
            "4-marker Screen",
            "4q12 deletion",
            "5-HT",
            "5-HIAA",
            "5-Hydroxytryptamine",
            "5-hydroxyindoleacetic Acid",
            "17-Hydroxyprogesterone",
            "17-OH Progesterone",
            "17-OHP",
            "24-Hour Urine Protein",
            "25-hydroxyvitamin D",
            "72 Hour Fecal Fat",
            "A/G Ratio",
            "A1AT",
            "A1c",
            "AAT",
            "ABGs",
            "ABO Group and Rh Type",
            "Absolute neutrophils",
            "ACA",
            "ACE",
            "Acetaminophen",
            "Acetoacetate",
            "Acetoacetic Acid",
            "Acetone",
            "Acetylcholine Receptor Antibody",
            "Acetylcholine Receptor Binding Antibody",
            "Acetylcholine Receptor Blocking Antibody",
            "Acetylcholine Receptor Modulating Antibody",
            "Acetylcholinesterase",
            "Acetylsalicylic Acid",
            "AChE",
            "AChR Antibody",
            "Acid-Fast Bacillus Smear and Culture and Sensitivity",
            "aCL Antibody",
            "ACPA",
            "ACR",
            "ACT",
            "ACTA",
            "ACTH",
            "ACTH Stimulation Test",
            "Actin Antibody",
            "Activated Clotting Time",
            "Activated Coagulation Time",
            "Activated Partial Thromboplastin Time",
            "Activated Protein C Resistance",
            "Acute Viral Hepatitis Panel",
            "Acute Viral Hepatitis Serology Panel",
            "AD",
            "ADA",
            "ADB",
            "Adenosine Deaminase",
            "Adenosine Deaminase, Fluid",
            "ADH",
            "ADN-B",
            "ADNase-B",
            "Adrenocorticotropic Hormone",
            "Aerobic Wound Culture",
            "AFB Smear and Culture",
            "AFB Testing",
            "AFP",
            "AFP Maternal",
            "AFP Tumor Markers",
            "AFP-L3%",
            "Agglutinins",
            "AGPA",
            "AIDS Screen",
            "AIDS Test",
            "ALA",
            "Alanine Aminotransferase",
            "Alanine Transaminase",
            "ALB",
            "Albumin",
            "Albumin to Globulin Ratio",
            "Albumin-to-Creatinine Ratio",
            "Albumin/Globulin Ratio",
            "Alcohol",
            "Aldolase",
            "Aldosterone",
            "Aldosterone and Plasma Renin Activity",
            "Aldosterone and Renin",
            "Aldosterone, Serum",
            "Aldosterone, Urine",
            "ALK Gene Fusion",
            "ALK Gene Rearrangement",
            "ALK Mutation",
            "ALK PHOS",
            "Alkaline Phosphatase",
            "Alkp",
            "Allergen-specific IgE Antibody Test",
            "Allergy Blood Testing",
            "Allergy Screen",
            "Alloantibody Identification",
            "ALP",
            "Alpha Tryptase",
            "Alpha-1 Antitrypsin",
            "Alpha-fetoprotein-L3 Percent",
            "Alpha-fetoprotein, Total",
            "Alpha1 Antitrypsin",
            "Alpha1-antitrypsin",
            "ALT",
            "Alzheimer Biomarkers",
            "AMA",
            "AMAS",
            "AMH",
            "AMH Hormone Test",
            "Amikacin",
            "Aminoglycoside Antibiotics",
            "Aminophylline",
            "Ammonia",
            "Ammonia, plasma",
            "Amnio",
            "Amniocentesis",
            "Amniotic Fluid Analysis",
            "Amy",
            "Amylase",
            "Amyloid Beta 42",
            "ANA",
            "Anaerobic Wound Culture",
            "ANCA",
            "ANCA Antibodies",
            "ANCA/MPO/PR3 Antibodies",
            "Androstenedione",
            "Angiotensin-Converting Enzyme",
            "Anion Gap",
            "Anti-Beta-2 Glycoprotein 1",
            "Anti-CCP",
            "Anti-citrulline Antibody",
            "Anti-cyclic Citrullinated Peptide",
            "anti-DNA",
            "Anti-DNase B",
            "Anti-double-stranded DNA, IgG",
            "Anti-dsDNA",
            "Anti-Endomysial Antibodies",
            "Anti-factor Xa Heparin",
            "Anti-FXa",
            "Anti-GPA",
            "Anti-HAV",
            "anti-HBc",
            "anti-HBc, IgM",
            "anti-HBe",
            "anti-HBs",
            "Anti-HCV",
            "Anti-Intrinsic Factor",
            "Anti-Jo-1",
            "Anti-Liver/Kidney Microsomal Antibodies Type 1",
            "Anti-LKM-1",
            "Anti-LKM1",
            "Anti-Mullerian Hormone",
            "Anti-Müllerian Hormone",
            "Anti-P450 2D6 Antibody",
            "Anti-parietal Cell Antibody",
            "Anti-Reticulin Antibodies",
            "Anti-retroviral Drug Resistance Testing",
            "Anti-Ribonucleoprotein",
            "Anti-RNP",
            "Anti-Saccharomyces cerevisiae mannan antibodies",
            "Anti-Sjögren Syndrome A",
            "Anti-Sjögren Syndrome B",
            "Anti-Sm",
            "Anti-Smooth Muscle Antibody",
            "Anti-SmRNP",
            "Anti-SSA",
            "Anti-SSB",
            "Anti-tissue Transglutaminase Antibody",
            "Anti-Topoisomerase",
            "Anti-TPO",
            "Anti-URNP",
            "Anti-Xa",
            "Antibodies to Saline-extracted Antigens",
            "Antibody ID, RBC",
            "Antibody Screen",
            "Antibody to ds-DNA",
            "Anticardiolipin Antibodies",
            "Anticentromere Antibody",
            "Anticytoplasmic Autoantibodies",
            "Antideoxyribonuclease-B Titer",
            "Antidiuretic Hormone",
            "Antihistidyl Transfer RNA Synthase Antibodies",
            "Antihistone Antibody",
            "Antimicrobial Susceptibility",
            "Antimicrosomal Antibody",
            "Antimitochondrial Antibody and Antimitochondrial M2 Antibody",
            "Antineutrophil Cytoplasmic Antibodies",
            "Antinuclear Antibody",
            "Antinuclear Antibody Panel",
            "Antiphospholipid Antibodies",
            "Antiphospholipids",
            "Antistreptolysin O Titer",
            "Antithrombin",
            "Antithyroglobulin Antibody",
            "Antithyroid Antibodies",
            "APA",
            "APC Resistance",
            "APCA",
            "Apo A",
            "Apo A-I",
            "Apo B",
            "APOE Cardiac Risk",
            "APOE Genotyping, Alzheimer Disease",
            "APOE Genotyping, Cardiovascular Disease",
            "APOE Genotyping, CVD",
            "Apolipoprotein A-I",
            "Apolipoprotein B",
            "Apolipoprotein B-100",
            "Apolipoprotein E Genotyping",
            "aPTT",
            "APTT",
            "ARA",
            "Arbovirus serology",
            "Arbovirus Testing",
            "Arbovirus Testing - IgM and IgG Antibodies, Nucleic Acid Amplification Tests",
            "Arginine Vasopressin",
            "Arterial Blood Gas Analysis",
            "Arterial Blood Gases",
            "Arthropod borne virus testing",
            "ARV Resistance Testing",
            "ASA",
            "ASCA",
            "ASLO",
            "ASMA",
            "ASO",
            "Aspartate Aminotransferase",
            "Aspartate Transaminase",
            "Aspirin",
            "AST",
            "AT 3",
            "AT III",
            "Autoantibodies",
            "Automated Immunoassays for Syphilis Antibodies",
            "AVP",
            "B Vitamins",
            "B-cell Gene Clonality Molecular Genetic Tests",
            "B-cell Gene Rearrangement",
            "B-cell Ig Gene Rearrangement",
            "B-cell Immunoglobulin Gene Rearrangement",
            "B-type Natriuretic Peptide",
            "B1",
            "B2",
            "B27",
            "B2M",
            "B3",
            "B5",
            "B6",
            "B7",
            "BAC",
            "Bacterial and Fungal Susceptibility Testing",
            "Bacterial Culture, respiratory",
            "Bacterial Culture, stool",
            "Bacterial Sputum Culture",
            "Bacterial Wound Culture",
            "BAL",
            "Basic Metabolic Panel",
            "BCGR",
            "BChE",
            "bcr-abl Oncogene",
            "BCR-ABL1",
            "BCR-ABL1 Fusion",
            "BCR/ABL",
            "Beta 2GP1 Ab",
            "Beta hCG",
            "Beta Tryptase",
            "Beta-2 Glycoprotein 1 Antibodies",
            "Beta-2 Glycoprotein 1 Antibodies IgG, IgM, and IgA",
            "Beta-2 Microglobulin Kidney Disease",
            "Beta-2 Microglobulin Tumor Marker",
            "Beta-hemolytic Strep Culture",
            "Beta-hydroxybutyrate",
            "Beta-hydroxybutyric Acid",
            "Beta2 Microglobulin, Serum or Urine",
            "Beta2 Microglobulin, Serum, Urine, or CSF",
            "Bicarb",
            "Bicarbonate",
            "Bilirubin",
            "Bilirubin - blood",
            "Bioavailable Testosterone",
            "Biochemical Markers of Bone Remodeling",
            "Biointact PTH",
            "Bismuth subsalicylate",
            "BLL",
            "Blood Alcohol Content",
            "Blood Alcohol Level",
            "Blood Cholesterol",
            "Blood Clotting Factors",
            "Blood Copper",
            "Blood Creatinine",
            "Blood Culture",
            "Blood Differential",
            "Blood Donation",
            "Blood Film",
            "Blood Gases",
            "Blood Glucose",
            "Blood Group",
            "Blood Ketones",
            "Blood Lead Level",
            "Blood Lead Test",
            "Blood Smear",
            "Blood Sugar",
            "Blood Transfusion",
            "Blood Typing",
            "Blood Urea Nitrogen",
            "BMP",
            "BNP",
            "BNP and NT-proBNP",
            "Body Fluid Analysis",
            "Bone Formation Markers",
            "Bone Markers",
            "Bone Marrow",
            "Bone Marrow Aspiration",
            "Bone Marrow Aspiration and Biopsy",
            "Bone Marrow Biopsy",
            "Bone Marrow Examination",
            "Bone Resorption Markers",
            "Bone Turnover Tests",
            "Bone-specific Alkaline Phosphatase",
            "Bordetella pertussis Antibodies",
            "Bordetella pertussis by PCR",
            "Bordetella pertussis Culture",
            "Borrelia burgdorferi Antibodies, IgM/IgG",
            "Borrelia burgdorferi DNA Detection by PCR",
            "Brain Natriuretic Peptide",
            "BRCA",
            "BRCA1 and BRCA2",
            "Breast Cancer Gene 1 and Breast Cancer Gene 2",
            "Breast Cancer Gene Expression Profiling",
            "Breast Cancer Gene Expression Tests",
            "Breast Cancer Multiparameter Gene Expression Tests",
            "Breast Cancer Susceptibility Genes 1 and 2",
            "Breast Cancer, Gene Expression",
            "BUN",
            "Butyrylcholinesterase",
            "C &",
            "C diff antigen",
            "c-ANCA",
            "c-erbB-2",
            "C-peptide",
            "C-Reactive Protein",
            "C-telopeptide",
            "C. diff",
            "C. difficile",
            "C. difficile Cytotoxin Assay",
            "C. difficile Toxin, A and B",
            "C1",
            "C1q",
            "C2",
            "C3",
            "C4",
            "CA 125 Tumor Marker",
            "CA 15-3",
            "CA 19-9",
            "CA 27.29",
            "CA-125",
            "CA-Breast",
            "CA-GI",
            "Caffeine",
            "Calcidiol",
            "Calcifidiol",
            "Calcitonin",
            "Calcitriol",
            "Calcium",
            "Calcofluor White Stain",
            "Calculated Glomerular Filtration Rate",
            "Calprotectin",
            "cANCA",
            "Cancer Antigen 125",
            "Cancer Antigen 15-3",
            "Cancer Antigen 19-9",
            "Cancer Antigen-Breast",
            "Cancer Antigen-GI",
            "Carbamazepine",
            "Carbohydrate Antigen 19-9",
            "Carbon Dioxide Content",
            "Carcinoembryonic Antigen",
            "Cardiac Biomarkers",
            "Cardiac CRP",
            "Cardiac Markers",
            "Cardiac Risk",
            "Cardiac Risk Assessment",
            "Cardiac-specific Troponin I and Troponin T",
            "Cardiolipin Antibodies",
            "Catecholamines",
            "Catecholamines, Plasma and Urine",
            "CBC",
            "CBC with Differential",
            "CCP Antibody",
            "CCT",
            "CD4 Count",
            "CD4 Lymphocyte Count",
            "CD4 Percent",
            "CEA",
            "Celiac Disease Antibody Tests",
            "Celiac Disease Tests",
            "Cell-Free Fetal DNA",
            "Cell-Free Fetal DNA Testing for Fetal Chromosomal Abnormalities",
            "Centromere Antibody",
            "Cerebrospinal Fluid Analysis",
            "Ceruloplasmin",
            "Ceruloplasmin, serum",
            "Cervical Smear",
            "Cervical/Vaginal Cytology",
            "CF DNA Analysis",
            "CF Gene Mutation Panel",
            "CF Molecular Genetic Testing",
            "CF Mutation Panel",
            "cffDNA",
            "CgA",
            "cGFR",
            "CH100",
            "CH50",
            "Chem 12",
            "Chem 7",
            "Chemistry Panel",
            "Chemistry Panels",
            "Chemistry Screen",
            "Chickenpox",
            "Chickenpox and Shingles Tests",
            "Chlamydia",
            "Chlamydia Testing",
            "Chlamydia trachomatis by Amplified Detection",
            "Chlamydia trachomatis by Direct Antigen Detection",
            "Chlamydia trachomatis Culture",
            "Chlamydia trachomatis DNA Probe",
            "Chloride",
            "Cholecalciferol",
            "Cholesterol",
            "Cholinesterase",
            "Cholinesterase Tests",
            "Chromogranin A",
            "Chromosome Analysis",
            "Chromosome Karyotype",
            "Chromosome Studies",
            "CHS",
            "Chymotrypsin",
            "Citrulline Antibody",
            "CK",
            "CK MB",
            "CK-MB",
            "CLO test",
            "Clopidogrel",
            "Clopidogrel Pharmacogenetic Testing",
            "Clostridium difficile",
            "Clostridium difficile and C. difficile Toxin Testing",
            "Clostridium difficile Culture",
            "Clotting Factors",
            "CMP",
            "CMV Blood Test",
            "CMV IgG",
            "CMV IgM",
            "CMV Tests",
            "CO2 Content",
            "CO2, Total",
            "Coagulation Cascade",
            "Coagulation Factors",
            "Cobalamin",
            "Cold Agglutinins",
            "Cold Autoantibodies",
            "Cold-Reacting Antibodies",
            "Complement",
            "Complement Activity",
            "Complement Component",
            "Complete Blood Count",
            "Comprehensive Metabolic Panel",
            "Conjugated Bilirubin",
            "Connecting Peptide Insulin",
            "Coombs, Direct",
            "Coombs, Indirect",
            "Copper",
            "Copper, 24-hour urine, total and free blood, and liver tissue",
            "Coproporphyrin",
            "Coronary Risk Panel",
            "Corrected Reticulocyte",
            "Corticotropin",
            "Cortisol",
            "Cosyntropin",
            "Cotinine",
            "CPK",
            "CPK MB",
            "CRCL",
            "Creat",
            "Creatine Kinase",
            "Creatine Kinase-MB",
            "Creatine Phosphokinase",
            "Creatinine",
            "Creatinine Clearance",
            "Creatinine Clearance, Urine",
            "Crit",
            "CRP",
            "CRP for heart disease",
            "CRP, high-sensitivity",
            "Cryocrit",
            "Cryoglobulins",
            "Cryoprotein",
            "CSF Analysis",
            "CSF Lactate",
            "CSF Protein Electrophoresis",
            "cTnI",
            "cTnT",
            "CTx",
            "Cu",
            "Culture - amniotic cells",
            "Culture - amniotic fluid",
            "Culture and Sensitivity",
            "Culture, blood",
            "Culture, sputum",
            "Culture, Throat",
            "Culture, Urine",
            "Culture, wound",
            "Cyclic Citrullinated Peptide Antibody",
            "Cyclosporine",
            "CYP2C19 Genotype",
            "CYP2C19 Sequence Genotype",
            "CYP2C9 Genotype",
            "Cystatin C",
            "Cystic Fibrosis Gene Mutation Panel",
            "Cystic Fibrosis Genotyping",
            "Cytogenetic Analysis",
            "Cytogenetics",
            "Cytomegalovirus",
            "Cytomegalovirus Antibody, IgG and IgM",
            "Cytomegalovirus by PCR",
            "Cytomegalovirus Culture",
            "D-dimer",
            "D-Xylose Absorption Test",
            "Darkfield Microscopy",
            "DAT",
            "DCP",
            "Deaminated Gliadin Peptide Antibodies",
            "Dehydroepiandrosterone Sulfate",
            "Delta-aminolevulinic Acid",
            "Dengue Antibodies",
            "Dengue Fever",
            "Dengue Fever Antibodies",
            "Dengue Fever Testing",
            "Dengue Fever Virus",
            "Dengue Virus by PCR",
            "Deoxypyridinoline",
            "Des-gamma-carboxy prothrombin",
            "Dexamethasone Suppression Test",
            "DGP",
            "DHEA Sulfate",
            "DHEA-SO4",
            "DHEAS",
            "Diabetes Autoantibodies",
            "Diabetes Mellitus Autoantibody Panel",
            "Diabetes-related Autoantibodies",
            "Diff",
            "Differential",
            "Differential Blood Count",
            "Differential Slide",
            "Digoxin",
            "Dilute Russell Viper Venom Test",
            "Direct Anti-human Globulin Test",
            "Direct Antiglobulin Test",
            "Direct Bilirubin",
            "Direct Coombs Test",
            "Direct LDL",
            "Direct LDL Cholesterol",
            "Direct LDL-C",
            "Direct Low-Density Lipoprotein Cholesterol",
            "Disaccharide Absorption Test",
            "DLDL",
            "Dopamine",
            "Double stranded DNA Antibody",
            "DPD",
            "Drug Resistance Testing",
            "Drug Screen",
            "Drug Test",
            "Drug Testing",
            "Drugs of Abuse Screen",
            "Drugs of Abuse Testing",
            "DRVVT",
            "DST",
            "E. coli",
            "E. coli non-O157",
            "E. coli O157",
            "E. coli O157 culture",
            "EA-D IgG Ab",
            "eAG",
            "EBNA-IgG Ab",
            "EBV Antibodies",
            "EBV VCA-IgG Ab",
            "EBV VCA-IgM Ab",
            "eGFR",
            "EGFR",
            "EGFR Mutation Testing",
            "Electrolyte Panel",
            "Electrolytes",
            "Electrophoresis",
            "EMA",
            "Emergency and Overdose Drug Testing",
            "Emergency/Overdose Drug Testing",
            "EML4-ALK Fusion Protein",
            "ENA Panel",
            "Endomysial Antibody",
            "Enteric Pathogens Culture, stool",
            "Epidermal Growth Factor Receptor",
            "Epidermal Growth Factor Receptor Mutation Analysis",
            "Epinephrine",
            "EPO",
            "Epstein-Barr Virus Antibodies",
            "Epstein-Barr Virus Antibody to Early D Antigen, IgG",
            "Epstein-Barr Virus Antibody to Nuclear Antigen, IgG",
            "Epstein-Barr Virus Antibody to Viral Capsid Antigen, IgM, IgG",
            "ER and PR Status",
            "erbB-1",
            "ERBB2",
            "Ergocalciferol",
            "Erythrocyte Acetylcholinesterase",
            "Erythrocyte Count",
            "Erythrocyte Morphology",
            "Erythrocyte Sedimentation Rate",
            "Erythropoietin",
            "ESR",
            "Essential Minerals",
            "Estimated Glomerular Filtration Rate",
            "Estradiol",
            "Estriol",
            "Estrogen and Progesterone Receptor Status",
            "Estrogen Fractions/fractionated",
            "Estrogen Receptors",
            "Estrogen/Progesterone Receptor Status",
            "Estrogen/Progesterone Receptors",
            "Estrogenic Hormones",
            "Estrogens",
            "Estrone",
            "Ethanol",
            "Ethyl Alcohol",
            "EtOH",
            "Extractable Nuclear Antigen Antibodies",
            "F-Actin Antibody",
            "Factor Assays",
            "Factor I",
            "Factor II 20210",
            "Factor II Mutation",
            "Factor V Leiden",
            "Factor V Leiden Mutation",
            "Factor V Leiden Mutation and PT 20210 Mutation",
            "Factor V R506Q",
            "FANA",
            "Fasting Blood Glucose",
            "Fasting Blood Sugar",
            "Fasting Insulin",
            "Fasting Plasma Glucose",
            "Fat Stain Oil Red O",
            "Fat, Fecal Qualitative or Quantitative",
            "Fat, Feces",
            "FBG",
            "FBS",
            "Fe Tests",
            "Fecal Calprotectin",
            "Fecal Fat",
            "Fecal Lactoferrin",
            "Fecal Occult Blood Test",
            "Fecal Occult Blood Test and Fecal Immunochemical Test",
            "Fecal WBC Non-microscopic",
            "Feces Culture",
            "FEP",
            "Ferritin",
            "Ferritin, serum",
            "Fetal Fibronectin",
            "Fetal Lung Maturity Tests",
            "fFN",
            "Fibrin Degradation Fragment",
            "Fibrinogen",
            "Fibrinogen Activity",
            "Fibrinogen Activity and Fibrinogen Antigen Assays",
            "Fibrinogen Antigen",
            "FIP1-like-1/platelet-derived growth factor alpha",
            "FIP1L1-PDGFRA",
            "FIP1L1-PDGFRA Fusion by FISH or RT-PCR",
            "First Trimester Down Syndrome Screen",
            "First Trimester Screen",
            "FIT",
            "FK506",
            "FLC",
            "Flu PCR",
            "Flu Test",
            "Flu Tests",
            "Fluorescent Antinuclear Antibody",
            "Fluorescent Treponemal Antibody Absorption Test",
            "FOBT",
            "Folate",
            "Folic Acid",
            "Follicle-stimulating Hormone",
            "Follicle-stimulating Hormone, serum or urine",
            "Follitropin",
            "FPG",
            "Fractionated Catecholamines",
            "Fractionated Plasma Free Metanephrines",
            "Fragment D-dimer",
            "Free Catecholamines, plasma and urine",
            "Free Copper",
            "Free Cortisol",
            "Free Erythrocyte Protoporphyrin",
            "Free Kappa/Lambda Ratio",
            "Free Light Chains",
            "Free PSA",
            "Free T3",
            "Free T3 and Total T3",
            "Free T4",
            "Free Testosterone",
            "Free Thyroxine",
            "Free Triiodothyronine",
            "Free Valproic Acid",
            "Fructosamine",
            "FSH",
            "FT3",
            "FTA-ABS",
            "Functional Antithrombin III",
            "Functional Fibrinogen",
            "Fungal Antigen and Antibody Tests",
            "Fungal Culture",
            "Fungal Molecular Tests",
            "Fungal Smear",
            "Fungal Tests",
            "G-6-PD",
            "G6PD",
            "GAD65 Autoantibodies",
            "GADA",
            "Gamma-Glutamyl Transferase",
            "Gamma-Glutamyl Transpeptidase",
            "Gamma-GT",
            "Gastric Parietal Cell Antibody",
            "Gastric Parietal Cell Antibody, IgG",
            "Gastrin",
            "GBS",
            "GC Test",
            "GDH",
            "Genetic Tests for Targeted Cancer Therapy",
            "Genital Human Papillomavirus",
            "Gentamicin",
            "German Measles",
            "gFOBT",
            "GFR",
            "GGT",
            "GGTP",
            "GH",
            "Glucose",
            "Glucose Tests",
            "Glucose-6-Phosphate Dehydrogenase",
            "Glutamate Dehydrogenase Test",
            "Glutamic Acid Decarboxylase Autoantibodies",
            "Glycated Hemoglobin",
            "Glycated Serum Protein",
            "Glycohemoglobin",
            "Glycosylated Hemoglobin",
            "Gonorrhea",
            "Gonorrhea Testing",
            "GOT",
            "GPT",
            "Gram Stain",
            "Gram's Stain",
            "Group A beta hemolytic streptococcus",
            "Group A streptococcus",
            "Group B Beta-hemolytic Streptococcus",
            "Group B Strep",
            "Group B Strep Screen",
            "Group B Streptococcus",
            "Growth Hormone",
            "Growth Hormone Stimulation Test",
            "Growth Hormone Suppression Test",
            "GSP",
            "GTP",
            "GTT",
            "Guaiac Smear Test",
            "H and H",
            "H pylori",
            "H-pylori",
            "H. pylori",
            "H. pylori antibody test",
            "H. pylori breath test",
            "H. pylori stool antigen test",
            "H. pylori Testing",
            "H1N1",
            "Haptoglobin",
            "HAV-Ab IgG",
            "HAV-Ab IgM",
            "HAV-Ab total",
            "Hb",
            "Hb ELP",
            "Hb IEF",
            "Hb S",
            "HbA1c",
            "HBeAg",
            "HBsAg",
            "HBV DNA",
            "HBV Tests",
            "hCG Pregnancy",
            "hCG Tumor Marker",
            "HCO3-",
            "Hct",
            "HCV-PCR",
            "HCV-RNA",
            "HDL",
            "HDL Cholesterol",
            "HDL Subclasses",
            "HDL Subfractions",
            "HDL-C",
            "Heavy Metals",
            "Heavy Metals Panel",
            "Helicobacter pylori",
            "Hematocrit",
            "Hemoccult",
            "Hemoglobin",
            "Hemoglobin A1c",
            "Hemoglobin by HPLC",
            "Hemoglobin Electrophoresis",
            "Hemoglobin Evaluation",
            "Hemoglobin Fractionation",
            "Hemoglobin Isoelectric Focusing",
            "Hemoglobin S",
            "Hemoglobin S Evaluation",
            "Hemoglobin-binding Protein",
            "Hemoglobinopathy Eval",
            "Hemoglobinopathy Evaluation",
            "Hemogram",
            "Hep B",
            "Heparin Activity",
            "Heparin Anti-Xa",
            "Heparin Associated Antibody",
            "Heparin Induced Antibody",
            "Heparin Level",
            "Heparin-induced Thrombocytopenia Antibody",
            "Heparin-induced Thrombocytopenia Platelet Factor 4 Antibody",
            "Heparin-PF4 Antibody",
            "Hepatic Copper",
            "Hepatic Function Panel",
            "Hepatitis A",
            "Hepatitis A Testing",
            "Hepatitis B",
            "Hepatitis B Core Antibody",
            "Hepatitis B e Antibody",
            "Hepatitis B e Antigen",
            "Hepatitis B Surface Antibody",
            "Hepatitis B Surface Antigen",
            "Hepatitis B Testing",
            "Hepatitis B Virus Testing",
            "Hepatitis C",
            "Hepatitis C Antibody",
            "Hepatitis C Testing",
            "Hepatitis C Viral Load",
            "Hepatitis C Virus Genotype",
            "Hepatitis Panel",
            "Hepatitis Screening Panel",
            "HER-1",
            "HER2 Overexpression by IHC",
            "HER2 Quantitative, Serum",
            "HER2 Serum",
            "HER2/neu",
            "HER2/neu Amplification by FISH",
            "Herpes",
            "Herpes Culture",
            "Herpes Simplex Viral Culture",
            "Herpes Simplex Virus, Type 1 and Type 2",
            "Herpes Testing",
            "Herpes Zoster",
            "HES/Leukemia",
            "Heterophile Antibodies",
            "Heterophile Antibody Test",
            "Heterophile Antibody Titer",
            "Hg",
            "Hgb",
            "Hgb S",
            "HGH",
            "HHV1",
            "HHV2",
            "HIAA",
            "High-density Lipoprotein Cholesterol",
            "High-risk HPV",
            "High-sensitivity C-reactive Protein",
            "High-sensitivity CRP",
            "Histamine",
            "Histocompatibility Testing",
            "Histone Antibody",
            "Histone Autoantibodies",
            "HIT Antibody",
            "HIT PF4 Antibody",
            "HIV Antibody",
            "HIV antigen",
            "HIV antigen/antibody combination testing",
            "HIV Genotypic Resistance",
            "HIV Genotypic Resistance Testing",
            "HIV NAAT",
            "HIV NAT",
            "HIV Nucleic Acid Amplification Test",
            "HIV PCR",
            "HIV Quantification",
            "HIV Serology",
            "HIV Viral Load",
            "HLA Antibody Testing/Screening/Identification",
            "HLA Crossmatching",
            "HLA Oligotyping",
            "HLA Sequence-based Typing",
            "HLA Testing",
            "HLA Typing",
            "HLA-B27",
            "HLA-B27 Antigen",
            "Homocysteine",
            "Homocysteine Cardiac Risk",
            "Hormone Receptor Status",
            "Hp",
            "HPT",
            "HPV",
            "HPV DNA",
            "HPV RNA",
            "HPV Test",
            "hrHPV",
            "hs-CRP",
            "hsCRP",
            "HSV by PCR",
            "HSV DNA",
            "HSV-1",
            "HSV-1 or HSV-2 IgM or IgG",
            "HSV-2",
            "HTLV",
            "HTLV-I/II Antibodies",
            "HTLV-I/II by PCR",
            "Human Calcitonin",
            "Human Chorionic Gonadotropin",
            "Human Chorionic Gonadotropin, quantitative",
            "Human Growth Hormone",
            "Human Immunodeficiency Virus Antibody Test",
            "Human Immunodeficiency Virus Genotypic Resistance Testing",
            "Human Immunodeficiency Virus RNA, Quantitative",
            "Human Leukocyte Antigen",
            "Human Leukocyte Antigen B27",
            "Human T-cell Lymphotropic Virus",
            "Human T-cell Lymphotropic Virus Types I/II by PCR",
            "Human T-Lymphotropic Virus Types I/II Antibodies",
            "Hydrogen Breath Test",
            "Hypofibrinogenemia Test",
            "IA-2A",
            "IAA",
            "IAT",
            "IBC",
            "ICA",
            "ICA512 Autoantibodies",
            "ICSH",
            "IF Antibody",
            "IF Antibody Type 1 or Type 2",
            "IFE",
            "iFOBT",
            "IgA",
            "IgE, Total",
            "IGF-1",
            "IgG",
            "IgM",
            "IGRA",
            "IL-6",
            "IMA",
            "Immunoassay FOBT",
            "Immunochemical FOBT",
            "Immunoelectrophoresis",
            "Immunofixation Electrophoresis",
            "Immunoglobulin A",
            "Immunoglobulin E",
            "Immunoglobulin G",
            "Immunoglobulin Gene Rearrangement",
            "Immunoglobulin M",
            "Immunoglobulins",
            "Immunoglobulins, Quantitative",
            "Immunophenotyping",
            "Immunophenotyping by Flow Cytometry or Immunohistochemistry",
            "Immunoreactive Trypsinogen",
            "Indirect Anti-human Globulin Test",
            "Indirect Antiglobulin Test",
            "Indirect Bilirubin",
            "Indirect Coombs Test",
            "Influenza A and B Culture",
            "Influenza Antigen Test",
            "Influenza Rapid Antigen Test",
            "Influenza Tests",
            "Influenza Type A and B Antigen Detection",
            "Influenza Type A H1N1",
            "Inhibin A",
            "Inorganic Phosphate",
            "INR",
            "Insulin",
            "Insulin Autoantibodies",
            "Insulin C-peptide",
            "Insulin-like Growth Factor - 1",
            "Insulin, serum",
            "Insulinoma-Associated-2 Autoantibodies",
            "Intact PTH",
            "Interferon Gamma Release Assays",
            "Interferon-gamma Release Assays",
            "Interleukin-6",
            "Interstitial Cell Stimulating Hormone",
            "Intrinsic Factor Antibody",
            "Intrinsic Factor Binding Antibody",
            "Intrinsic Factor Blocking Antibody",
            "Ionized Calcium",
            "Iontophoretic Sweat Test",
            "Iron",
            "Iron Binding Capacity",
            "Iron Indices",
            "Iron Tests",
            "Iron, serum",
            "IRT",
            "Ischemia-Modified Albumin",
            "Islet Autoantibodies",
            "Islet Cell Cytoplasmic Autoantibodies",
            "JAK2 Exon 12 Mutation",
            "JAK2 Mutation",
            "JAK2 V617F",
            "Janus Kinase 2",
            "Joint Fluid Analysis",
            "K",
            "K-Ras",
            "Kappa and Lambda Free Light Chains",
            "Kappa/Lambda Ratio",
            "Karyotype",
            "Karyotyping",
            "Ketone Bodies",
            "Ketones, blood",
            "Kidney Function Panel",
            "Kidney Panel",
            "Kidney Stone Analysis",
            "Kidney Stone Risk Panel",
            "KOH Prep",
            "KRAS Mutation",
            "KRAS Mutation Analysis",
            "L-Lactate",
            "LA",
            "LA Sensitive PTT",
            "LAC",
            "Lactate",
            "Lactate Dehydrogenase",
            "Lactic Acid",
            "Lactoferrin",
            "Lactose Breath Test",
            "Lactose Tolerance Test",
            "Lactose Tolerance Tests",
            "Latent Tuberculosis Infection Test",
            "LD",
            "LDH",
            "LDL",
            "LDL Cholesterol",
            "LDL Count",
            "LDL D",
            "LDL Particle Number",
            "LDL Particle Size",
            "LDL Particle Testing",
            "LDL Pattern",
            "LDL Subclasses",
            "LDL Subfractions",
            "LDL-C",
            "LDL-P",
            "Lead",
            "Lead, blood",
            "Legionella",
            "Legionella Antigen, urine",
            "Legionella by PCR",
            "Legionella Culture",
            "Legionella pneumophila",
            "Legionella Testing",
            "Legionnaires Disease Testing",
            "Leptin",
            "Leukocyte Count",
            "Leukocyte Differential",
            "Leukocyte Differential Count",
            "Levetiracetam",
            "LFTs",
            "LH",
            "Light Chains, Free",
            "Lipase",
            "Lipid Panel",
            "Lipid Profile",
            "Lipoprotein",
            "Lipoprotein little a",
            "Lipoprotein-associated Phospholipase A2",
            "Lithium",
            "Liver Function Tests",
            "Liver Kidney Microsomal Type 1 Antibodies",
            "Liver Kidney Microsome Type 1 Antibodies",
            "Liver Panel",
            "LKM1 Antibodies",
            "Low-Density Lipoprotein Cholesterol",
            "Low-Density Lipoprotein Subfraction Profile",
            "Lp",
            "Lp-PLA2",
            "Lp-PLA2 Activity Test",
            "LpPLA2",
            "LPS",
            "Lupus Anticoagulant",
            "Lupus Anticoagulant Panel",
            "Lupus Anticoagulant Testing",
            "Lupus Inhibitor",
            "Luteinizing Hormone",
            "Luteinizing Hormone, serum or urine",
            "Lutropin",
            "Lyme Antibodies Detection",
            "Lyme Antibodies IgM/IgG by Western Blot",
            "Lyme Disease",
            "Lyme Disease Tests",
            "Lytes",
            "Mag",
            "Magnesium",
            "Magnesium salicylate",
            "Mantoux",
            "Manual Differential",
            "Mast Cell Tryptase",
            "Maternal Serum AFP",
            "Maternal Serum Screen",
            "Mature Tryptase",
            "MCH",
            "MCHC",
            "MCV",
            "Mean Platelet Volume",
            "Measles",
            "Measles and Mumps Tests",
            "Measles Antibody, IgM and IgG",
            "Measles Blood Test",
            "Measles by RT-PCR",
            "Measles Immunity Test",
            "Measles Viral Culture",
            "Mercury",
            "Mercury, Urine and Blood",
            "Metabolites",
            "Metanephrine and Normetanephrine",
            "Metanephrines",
            "Methicillin resistant Staphylococcus aureus Screening",
            "Methotrexate",
            "Methyl salicylate",
            "Methylenetetrahydrofolate Reductase Mutations, C677T and A1298C",
            "Methylmalonic Acid",
            "Mg",
            "MHA-TP",
            "Microalbumin",
            "Microhemagglutination Assay",
            "Microminerals",
            "Micronutrients",
            "MIF",
            "MIH",
            "MIS",
            "Mitochondrial Antibody",
            "MMA",
            "MMF",
            "Modified Russell Viper Venom Test",
            "Mono Test",
            "Mononuclear Heterophile Test",
            "Mononucleosis Spot Test",
            "Monospot",
            "MPA",
            "MPO",
            "MPO-ANCA",
            "MPV",
            "MRSA Screening",
            "MRVVT",
            "msAFP",
            "MSAFP",
            "MTHFR DNA Testing",
            "MTHFR Mutation",
            "MTX",
            "Müllerian Inhibiting Factor",
            "Müllerian-inhibiting Hormone",
            "Müllerian-Inhibiting Substance",
            "Multiple Marker Test",
            "Mumps",
            "Mumps Antibody, IgM and IgG",
            "Mumps Blood Test",
            "Mumps by RT-PCR",
            "Mumps Immunity Test",
            "Mumps Viral Culture",
            "Muscle nicotinic Acetylcholine Receptor Binding Antibody",
            "Myasthenia Gravis Antibodies",
            "Mycobacteria Culture",
            "Mycobacteria Smear",
            "Mycobacteria tuberculosis Nucleic Acid Amplification Test",
            "Mycology Tests",
            "Mycophenolate Mofetil",
            "Mycophenolate Sodium",
            "Mycophenolic Acid",
            "Mycoplasma",
            "Mycoplasma by PCR",
            "Mycoplasma Culture",
            "Mycoplasma Culture, genital source",
            "Mycoplasma DNA Testing",
            "Mycoplasma pneumoniae Culture",
            "Mycoplasma pneumoniae IgG and IgM Antibodies",
            "Myeloperoxidase Antibodies",
            "Myoglobin",
            "N-telopeptide",
            "N-terminal pro b-type Natriuretic Peptide",
            "Na",
            "Native double-stranded DNA Antibody",
            "Natriuretic Peptides",
            "Neisseria gonorrhoeae by Amplified Detection",
            "Neisseria gonorrhoeae Culture",
            "Neisseria gonorrhoeae DNA Probe",
            "Neisseria gonorrhoeae Gram Stain",
            "Neonatal Bilirubin",
            "NH3",
            "Nicotine",
            "Nicotine / Cotinine",
            "Nicotine &",
            "NIPT",
            "Non-Invasive Prenatal Testing",
            "Norepinephrine",
            "NT-proBNP",
            "NTx",
            "O&P",
            "Occult Blood Test, Fecal",
            "OGTT",
            "Oral Glucose Tolerance Test",
            "Oral Lactose Tolerance",
            "Osmolality",
            "Osteocalcin",
            "Ova and Parasite Exam",
            "P",
            "p-ANCA",
            "P1NP",
            "p24",
            "p24 Antigen",
            "p24 antigen capture assay",
            "p24 capsid or core antigen",
            "p24 protein",
            "Packed Cell Volume",
            "PAF-AH",
            "pANCA",
            "Pap Smear",
            "Pap Test",
            "Papanicolaou Test",
            "PAPP-A",
            "Paracetamol",
            "Parasitic Examination, Stool",
            "Parathormone",
            "Parathyroid Hormone",
            "Parietal Cell Antibody",
            "Parotitis",
            "Partial Thromboplastin Time",
            "Parvo B19",
            "Parvovirus",
            "Parvovirus B19",
            "PBG",
            "PCHE",
            "PCR for Influenza Virus",
            "PCT",
            "PCV",
            "PDGFRA-FIP1L1 gene rearrangement",
            "PDW",
            "Pericardial Fluid Analysis",
            "Peripheral Blood Smear",
            "Peripheral Differential",
            "Peripheral Smear",
            "Peritoneal Fluid Analysis",
            "Pertussis",
            "Pertussis Tests",
            "PFA",
            "PFT",
            "PGSN",
            "Pharmacogenetic Tests",
            "Phenobarbital",
            "Phenytoin",
            "Phenytoin, total and free",
            "Philadelphia Chromosome",
            "Phosphate",
            "Phosphorus",
            "PIVKA II",
            "PLAC",
            "Plasma Cholinesterase",
            "Plasma Fibrinogen",
            "Plasma Free Metanephrines",
            "Plasma Ketone",
            "Plasma Metanephrines",
            "Plasma Total Homocysteine",
            "Platelet Aggregation Studies",
            "Platelet Count",
            "Platelet Distribution Width",
            "Platelet Function Assay",
            "Platelet Function Tests",
            "Platelet-activating Factor Acetylhydrolase",
            "Pleural Fluid Analysis",
            "PLT",
            "PML-RARA",
            "PO4",
            "Poison Testing",
            "Porphobilinogen",
            "Porphyrin Tests",
            "Porphyrins",
            "Potassium",
            "Potassium Hydroxide Preparation",
            "Potassium, blood or urine",
            "PPD",
            "PR3",
            "PR3-ANCA",
            "PRA",
            "Prealbumin",
            "Pregnancy Test",
            "Pregnenolone",
            "Prenatal Group B Strep Screening",
            "Prenatal Group B Streptococcus Screening",
            "Presenilin 1 Gene",
            "PRL",
            "Pro Time",
            "proBNP",
            "Procalcitonin",
            "Procollagen Type 1 N-Terminal Propeptide",
            "Progesterone",
            "Progesterone Receptors",
            "Proinsulin C-peptide",
            "Prolactin",
            "Promyelocytic Leukemia/Retinoic Acid Receptor Alpha",
            "Prostate Specific Antigen",
            "Protein C",
            "Protein C Activity",
            "Protein C and Protein S",
            "Protein C Level",
            "Protein C, Functional or Antigen",
            "Protein Electrophoresis",
            "Protein ElectrophoresisImmunofixation Electrophoresis",
            "Protein ELP",
            "Protein S",
            "Protein S Activity",
            "Protein S Level",
            "Protein S, Functional or Antigen",
            "Protein Tyrosine Phosphatase-like Autoantibodies",
            "Proteinase 3 Antibodies",
            "Prothrombin 20210 Mutation",
            "Prothrombin Time",
            "Prothrombin Time and International Normalized Ratio",
            "Protime",
            "Protoporphyrin",
            "PS-1",
            "PS1",
            "PS1 or PSEN1 Genetic Mutation Analysis",
            "PSA",
            "PSEN1",
            "Pseudocholinesterase",
            "PT",
            "PT 20210",
            "PT G20210A",
            "PTH",
            "PTT",
            "PTT-LA",
            "Purified Protein Derivative",
            "Pyridinium Crosslinks",
            "Quad Screen",
            "Quadruple Marker Test",
            "Qualitative hCG",
            "Qualitative or Quantitative Stool Fat",
            "QuantiFERON®-TB Gold",
            "QuantiFERON®-TB Gold In-Tube",
            "Quantitative hCG",
            "Quantitative IgE",
            "Quantitative Immunoglobulin A",
            "Quantitative Immunoglobulins",
            "Quantitative Plasma RNA Test",
            "Quantitative Serum Free Light Chains with Ratio",
            "RADT",
            "Rapamycin",
            "Rapid Antigen Detection Test",
            "Rapid Flu Test",
            "Rapid Influenza Diagnostic Test",
            "Rapid Plasma Reagin",
            "Rapid Strep Test",
            "Rapid urease test for H. pylori",
            "RBC",
            "RBC Ab ID",
            "RBC Antibody ID",
            "RBC Antibody Identification",
            "RBC Antibody Screen",
            "RBC Cholinesterase",
            "RBC Count",
            "RBC Folate",
            "RBC G6PD test",
            "RDW",
            "Red Blood Cell Antibody Identification",
            "Red Blood Cell Antibody Screen",
            "Red Blood Cell Count",
            "Red Blood Cell Morphology",
            "Red Cell Cholinesterase",
            "Red Cell Indices",
            "Red Count",
            "Renal Calculus Analysis",
            "Renal Function Panel",
            "Renal Panel",
            "Renin",
            "Respiratory Culture",
            "Respiratory Syncytial Virus",
            "Retic Count",
            "Reticulocyte Count",
            "Reticulocyte Index",
            "Reticulocyte Percent",
            "Reticulocyte Production Index",
            "Retinol",
            "RF",
            "Rh Factor",
            "Rheumatoid Factor",
            "RIDT",
            "Ristocetin Cofactor",
            "RPI",
            "RPR",
            "RSV",
            "RSV Testing",
            "Rubella",
            "Rubella Antibodies, IgM and IgG",
            "Rubella Test",
            "Rubeola",
            "S",
            "S182",
            "Saccharomyces cerevisiae Antibodies, IgG or IgA",
            "SACE",
            "Salicylates",
            "Salicylates, blood",
            "Salivary Cortisol",
            "Salsalate",
            "Scl-70",
            "Scleroderma Antibodies",
            "sdLDL",
            "Second Trimester Maternal Serum Screening",
            "Second Trimester Screen",
            "Sed Rate",
            "Sedimentation Rate",
            "Semen Analysis",
            "Seminal Fluid Analysis",
            "Sensitivity Testing",
            "Serine Protease 3",
            "Serotonin",
            "Serotonin Metabolite",
            "Serum Angiotensin Converting Enzyme",
            "Serum Creatinine",
            "Serum Fe",
            "Serum Ferritin",
            "Serum Free Light Chains",
            "Serum Glutamic-Oxaloacetic Transaminase",
            "Serum Glutamic-Pyruvic Transaminase",
            "Serum Iron",
            "Serum Iron-Binding Capacity",
            "Serum Ketone",
            "Serum myoglobin",
            "Serum Protein Electrophoresis",
            "Serum Transferrin Receptors",
            "Serum Trypsinogen",
            "Serum Urate",
            "Sex Hormone Binding Globulin",
            "SFLC",
            "SGOT",
            "SGPT",
            "SHBG",
            "Shiga toxin-producing Escherichia coli",
            "Shiga-like toxin by EIA",
            "Shingles",
            "Sickle Cell Screen",
            "Sickle Cell Tests",
            "Siderophilin",
            "Sirolimus",
            "SMA",
            "SMA 12",
            "SMA 20",
            "SMA 7",
            "SMAC",
            "SMAC7",
            "Smith Antibody",
            "Smooth Muscle Antibody",
            "SMRP",
            "Sodium",
            "Sodium salicylate",
            "Soluble Mesothelin-Related Peptides",
            "Soluble Transferrin Receptor",
            "Somatomedin C",
            "Somatotropin",
            "SPE",
            "SPEP",
            "Sperm Analysis",
            "Sperm Count",
            "Spinal Fluid Analysis",
            "Sports Doping Tests",
            "Sputum Culture",
            "Sputum Culture, routine bacterial",
            "SSA",
            "SSB",
            "STEC",
            "sTfR",
            "Stool Calprotectin",
            "Stool Culture",
            "Stool Lactoferrin",
            "Stool Lipids",
            "Stool Occult Blood",
            "Stool Trypsin and Chymotrypsin",
            "Strep Group B",
            "Strep Throat Test",
            "Streptococcal Screen",
            "Stx gene detection by PCR",
            "Substance Abuse Testing",
            "Susceptibility Testing",
            "Sweat Chloride",
            "Sweat Electrolytes",
            "Sweat Test",
            "Synovial Fluid Analysis",
            "Syphilis",
            "Syphilis Detection Tests",
            "Syphilis Tests",
            "T-cell Gene Clonality",
            "T-Cell Receptor Gene Rearrangement",
            "T-helper Cells",
            "T-Spot®.TB",
            "T. vaginalis",
            "T3",
            "T4",
            "T4 Count",
            "TAC",
            "Tacrolimus",
            "Tartrate-resistant Acid Phosphatase",
            "Tau Protein and Amyloid Beta 42 Peptide",
            "Tau/Aß42",
            "TB Culture and Sensitivity",
            "TB NAAT",
            "TB Screening Tests",
            "TBII",
            "TBIL",
            "TCGR",
            "TCO2",
            "TCR Gene Rearrangement",
            "TDM",
            "TeBG",
            "Testosterone",
            "Testosterone-estrogen Binding Globulin",
            "TfR",
            "Tg",
            "TG",
            "TgAb",
            "Theophylline",
            "Theophylline and Caffeine",
            "Therapeutic Drug Monitoring",
            "Thiopurine methyltransferase",
            "Thiopurine S-methyltransferase Genotype",
            "Thiopurine S-methyltransferase Phenotype",
            "Three-day Measles",
            "Throat Culture",
            "Thrombin Clotting Time",
            "Thrombin Time",
            "Thrombocyte Count",
            "Thymotaxin",
            "Thyrocalcitonin",
            "Thyroglobulin",
            "Thyroglobulin Antibody",
            "Thyroglobulin, Serum or Plasma",
            "Thyroid Antibodies",
            "Thyroid Autoantibodies",
            "Thyroid Function Panel",
            "Thyroid Microsomal Antibody",
            "Thyroid Panel",
            "Thyroid Peroxidase Antibody",
            "Thyroid Stimulating Hormone Receptor Antibody",
            "Thyroid Stimulating Immunoglobulin",
            "Thyroid-stimulating Hormone",
            "Thyroperoxidase Antibody",
            "Thyrotropin",
            "Thyrotropin Receptor Antibodies",
            "Thyroxine",
            "Thyroxine-binding Prealbumin",
            "TIBC",
            "TIBC, UIBC, and Transferrin",
            "Tissue Transglutaminase Antibody",
            "Tissue Typing",
            "TnI",
            "TnT",
            "Tobramycin",
            "TORCH",
            "TORCH Panel",
            "TORCH Test",
            "Total AFP",
            "Total beta hCG",
            "Total Bilirubin",
            "Total Calcium",
            "Total Carbamazepine",
            "Total Cholesterol",
            "Total CK",
            "Total CO2",
            "Total Complement",
            "Total hCG",
            "Total Hemolytic Complement Activity",
            "Total IgA",
            "Total IgE",
            "Total Immunoglobulins",
            "Total Iron Binding Capacity",
            "Total Protein",
            "Total Protein and A/G Ratio",
            "Total PSA",
            "Total Testosterone",
            "Total Triiodothyronine",
            "Total Tryptase",
            "Tox Screen",
            "Toxic Metals",
            "Toxicology Assays",
            "Toxicology Screen",
            "Toxoplasma gondii Antibodies, IgG, IgM",
            "Toxoplasma gondii Molecular Detection by PCR",
            "Toxoplasma gondii, T. gondii",
            "Toxoplasmosis",
            "Toxoplasmosis Testing",
            "TP",
            "TPMT",
            "TPMT Genotype",
            "TPMT Phenotype",
            "TPMT RBC",
            "TPO",
            "TPPA",
            "TRAb",
            "Trace Elements",
            "Trace Minerals",
            "Transferrin",
            "Transferrin Receptor",
            "Transferrin Saturation",
            "Transthyretin",
            "TRAP",
            "Treponema pallidum by PCR",
            "Treponema pallidum Particle Agglutination Assay",
            "Trichomonas",
            "Trichomonas Testing",
            "Trichomonas vaginalis",
            "Trichomonas vaginalis by Amplified Detection",
            "Trichomonas vaginalis by Direct Fluorescent Antibody",
            "Trichomonas vaginalis Culture",
            "Trichomonas vaginalis DNA Probe",
            "Trichomonas vaginalis RNA",
            "TRIG",
            "Triglycerides",
            "Triiodothyronine",
            "Triple Screen",
            "Triple Test",
            "Troponin",
            "Trypsin",
            "Trypsin and Chymotrypsin",
            "Trypsin-like Immunoreactivity",
            "Trypsinogen",
            "Tryptase",
            "TSH",
            "TSH Receptor Antibody",
            "TSI",
            "TT",
            "tTG",
            "tTG Antibody",
            "tTGA",
            "Tuberculin Skin Test",
            "Tumor Markers",
            "UA",
            "UACR",
            "UIBC",
            "Ultra-sensitive CRP",
            "Unconjugated Bilirubin",
            "Unsaturated Iron Binding Capacity",
            "UP/CR",
            "UPCR",
            "UPE",
            "UPEP",
            "Urea",
            "Urea breath test",
            "Urea Nitrogen",
            "Ureaplasma Culture",
            "Uric Acid",
            "Urinalysis",
            "Urinary Cortisol",
            "Urinary Stone Analysis",
            "Urine Albumin",
            "Urine Albumin and Albumin/Creatinine Ratio",
            "Urine Analysis",
            "Urine C and S",
            "Urine Calcium, Urine Oxalate, Urine Uric Acid, Urine Citric Acid , Urine Creatinine, Renal Stone Risk Panel, Urine Supersaturation Profile",
            "Urine Copper",
            "Urine Creatinine",
            "Urine Culture",
            "Urine Culture and Sensitivity",
            "Urine Glucose",
            "Urine Homocysteine",
            "Urine Metanephrines",
            "Urine Metanephrines, Total and Fractionated",
            "Urine myoglobin",
            "Urine Protein",
            "Urine Protein and Urine Protein to Creatinine Ratio",
            "Urine Protein Electrophoresis",
            "Urine Protein to Creatinine Ratio",
            "Urine Test",
            "Urine Total Protein",
            "Uroporphyrin",
            "Valproate",
            "Valproic Acid",
            "Vancomycin",
            "Vanillylmandelic Acid, urine",
            "VAP",
            "Varicella Zoster Virus",
            "Varicella Zoster Virus Antibodies, IgG and IgM",
            "Varicella Zoster Virus by DFA",
            "Varicella Zoster Virus by PCR",
            "Varicella Zoster Virus Culture",
            "Vasopressin",
            "VDRL",
            "Venereal Disease Research Laboratory",
            "Very Low-Density Lipoprotein Cholesterol",
            "Viral Hepatitis A Antibody",
            "Viral Hepatitis C Antibody Screen",
            "Viral Hepatitis C RNA by PCR",
            "Viral Hepatitis Panel",
            "Vitamin A",
            "Vitamin B complex",
            "Vitamin B12",
            "Vitamin B12 and Folate",
            "Vitamin D",
            "Vitamin D Tests",
            "Vitamin K",
            "VKORC1 Genotype",
            "VLDL",
            "VLDL Cholesterol",
            "VLDL-C",
            "VMA",
            "VMAU",
            "von Willebrand Factor",
            "von Willebrand Factor Antigen and von Willebrand Factor Activity",
            "von Willebrand Panel",
            "VWF:Ag",
            "VWF:RCo",
            "VZV",
            "Warfarin Sensitivity Genotyping",
            "Warfarin Sensitivity Testing",
            "WBC",
            "WBC Count",
            "WBC Count Differential",
            "WBC Differential",
            "West Nile Virus",
            "West Nile Virus Testing",
            "West Nile Virus, IgM and IgG Antibodies and Nucleic Acid Amplification Tests",
            "Westergren Sedimentation Rate",
            "Wet Prep",
            "White Blood Cell Count",
            "White Blood Cell Differential",
            "White Count",
            "Whooping Cough",
            "Whooping Cough Tests",
            "Widal Test",
            "WNV by NAAT",
            "WNV Tests",
            "Wound Culture",
            "Xa Inhibition",
            "Xylose Absorption",
            "Xylose Absorption Test",
            "Xylose Tolerance Test",
            "Zinc Protoporphyrin",
            "ZP",
            "ZPP",
            "ZPP/Heme Ratio",
            "αantitrypsin"};
    public static String[] visit_type = {"Visit type...", "Out patient", "In patient"};
    public static String[] labs = {"Choose LAB", "lab 1", "lab 2", "lab 3"};
}
